# profiles/local/config.yaml
executor: local
cores: 8
jobs: 100
use-conda: true
rerun-incomplete: true
printshellcmds: true
latency-wait: 120
default-resources:
  - mem_mb=8000
  - disk_mb=10000
restart-times: 1
keep-going: true
