# profiles/slurm/config.yaml
# Snakemake SLURM configuration for local execution with conda support

jobs: 20
use-conda: false
rerun-incomplete: true
printshellcmds: true
latency-wait: 180
keep-going: true
verbose: true

# Default resources for all jobs
default-resources:
  - threads=8
  - mem_mb=40000
  - runtime=8h

restart-times: 1
max-status-checks-per-second: 10
