# profiles/slurm/config.yaml
# Snakemake SLURM configuration for local execution within a Slurm allocation.

jobs: 40
use-conda: false
rerun-incomplete: true
printshellcmds: true
latency-wait: 180
keep-going: true
verbose: true

# Default resources for all jobs
default-resources:
  - threads=16
  - mem_mb=20000
  - runtime=24h

restart-times: 1
max-status-checks-per-second: 100
